FROM node:22-alpine3.22

RUN apk add --no-cache \
# Video capture and processing
  ffmpeg \
# Processing demo image artifacts
  imagemagick \
# Terminal syntax highlighting
  bash \
# Version control
  git \ 
# Git syntax highlighting
  less \
# Git commit signing
  gpg \
# GitHub CLI tool
  github-cli \
# Text editor
  vim \
# Oxipng is a multithreaded lossless PNG/APNG compression optimizer
  oxipng

USER node